version: "3.9"

networks:
  flashbots-devnet_default:
    external: true

services:

  # deploy smart contracts & save deployment to file (./deployments/local.json on localhost)
  run-deploy:
    image: "flashbots/mev-flood"
    command:
      - init
      - -r http://host.docker.internal:8545
      - -s local.json
    volumes:
      - ./deployments:/app/cli/deployments

  # start sending swaps using the deployment file created in the last step
  spam:
    image: "flashbots/mev-flood"
    command:
      - spam
      - -r http://host.docker.internal:8545
      - -l local.json
    volumes:
      - ./deployments:/app/cli/deployments
    depends_on:
      beacon-chain:
        condition: service_completed_successfully