version: "3.9"

networks:
  flashbots-devnet_default:
    external: true

services:

  # deploy smart contracts & save deployment to file (./deployments/local.json on localhost)
  run-deploy:
    image: "flashbots/mev-flood"
    command:
      - init
      - --rpcUrl=http://geth:8545
      - --saveFile=local.json
    volumes:
      - ./deployments:/app/cli/deployments
    networks: [ flashbots-devnet_default ]
    healthcheck:
      # check last contract deployed successfully
      test: ["CMD-SHELL", "curl -s http://geth:8545 -H 'Content-Type: application/json' --data-binary '{\"jsonrpc\":\"2.0\",\"method\":\"eth_getCode\",\"params\":[\"0xa31AaBfCfcC7617379C87487cDaBF79f770F3D72\", \"latest\"],\"id\":1}' | jq -e '.result != \"0x\"'"]
      interval: 5s
      timeout: 3s
      retries: 3

  # start sending swaps using the deployment file created in the last step
  spam:
    image: "flashbots/mev-flood"
    command:
      - spam
      - --rpcUrl=http://geth:8545
      - --loadFile=local.json
    volumes:
      - ./deployments:/app/cli/deployments
    depends_on:
      run-deploy:
        condition: service_completed_successfully
    networks: [ flashbots-devnet_default ]